### ISSUE TITLE
Module '"./deps"' has no exported member X deno-ts(2305)

### ISSUE THREAD

**Issue by ppozniak** [discordeno/boilerplate#100]
Hello.
Just started using the boilerplate, but project is full of errors because
`Module '"./deps"' has no exported member 'Message'.deno-ts(2305)`
Basically all imports from ./deps have this error.

```
deno 1.7.2 (release, x86_64-apple-darwin)
v8 8.9.255.3
typescript 4.1.3
```

**Comment by itohatweb** [comment]
This is most likely because you don't have the modules cached. Run `deno cache mod.ts` and then reload your vsc.

**Comment by itohatweb** [comment]
For better help I would recommend you to join our Discord server: https://discord.gg/5vBgXk3UcZ
