### ISSUE TITLE
Hot reload

### ISSUE THREAD

**Issue by ppozniak** [discordeno/boilerplate#101]
Readme mentioned
```
**Hot Reloadable**

- Easily update your code without having to restart the bot everytime.
```

However I can't seem to make it work, nor I see a sight of `denon` or anything else that would make it realoadable.
Is it just readme error, or it should be working?

```
deno 1.7.2 (release, x86_64-apple-darwin)
v8 8.9.255.3
typescript 4.1.3
```

**Comment by itohatweb** [comment]
What we mean by this: You can edit most of the files like a command but then you don't have to restart your bot but you can just send this message `!reload commands`.

**Comment by ayntee** [comment]
> Readme mentioned
> 
> ```
> **Hot Reloadable**
> 
> - Easily update your code without having to restart the bot everytime.
> ```
> 
> However I can't seem to make it work, nor I see a sight of `denon` or anything else that would make it realoadable.
> Is it just readme error, or it should be working?
> 
> ```
> deno 1.7.2 (release, x86_64-apple-darwin)
> v8 8.9.255.3
> typescript 4.1.3
> ```

If you want to "watch" for file changes, simply add the `--watch` flag to `deno run` command.

**Comment by ppozniak** [comment]
Alright thanks, I'll add it to the readme if that's okay with you
