### ISSUE TITLE
Change Command Execution and Error Handling

### ISSUE THREAD

**Issue by MilSci** [discordeno/boilerplate#103]
I was thinking of an idea that could be beneficial to people using the boiler plate by dividing the `createCommand` function into more parts (extending the `command: any` parameter). It would establish 3 sections

1. preExecution
2. execution
3. postExecution

The following code will be necessary to understand the explanation:
```ts
interface CommandResult {
  code: "OK" | "FAIL";
  payload?: any;
  metadata?: string; //If there is an error made, or something you want the postExecution to have note of write it here
}
```
- In general, each part would return the `CommandResult` interface except for the `postExecution`. The `preExecution` would establish any variables, database connections and requests, html requests, etc. and pass the preferred variables into the `payload` property of the `CommandResult` that will be returned.

- At that point, the `execution` part would use the `payload` variables to do any of the main `execution`, aka the brains of the command. (Variable manipulation, sending messages, etc.) Again, it would return the `CommandResult`, it can choose to put data in the `payload` property, however, it is not necessary.

- The `postExecution` would them come into action and close any database connections if necessary, etc. At the same time, it would produce an error, whether it be sending an embed or something similar, if it receives a `"FAIL"` code.

**Quick Note**
Each part should be able to check the code and payload, so if the `CommandResult` code is a `"FAIL"` or the `payload` returns undefined, it can skip to the next part. Once it reaches the `postExecution` then an error would be developed and sent however deemed appropriate.

**Conclusion**
This would divide up a command into several parts and enable chaining as well as effective error checking. Data could be chained down, separating variables, execution, and error sending. Also by just returning undefined or `"FAIL"` all errors can be addressed in `postExecution`. If I need to explain more because I was terrible at explaining, please let me know I'd be glad to talk or write it out further.

**Comment by Bavfalcon9** [comment]
This seems redundant, preExecution can be handled by using `execution`. The only use case I see from this issue is a callback or closure for handling errors executed with a command. However for your other suggestion, it sounds like you want something enabling you to customize the parameters passed to the execution function, which would be cool.

**Comment by ayntee** [comment]
Any useful use-case for this?

**Comment by itohatweb** [comment]
> Any useful use-case for this?

Yes pls explain that.

Anyways my two cents from how I understood it:
- Usually you don't want to open a new db connection for every command execute
- Also often you first check if the user even is allowed to access this data which is usually done mid execution. 
- Next new users could be confused by seeing 3 different execution functions and what they need to pass
- If `postExecution` should handle all errors in this way this would just make it more complicated to handle errors imo cause then you need to do sth like this: 
```ts
try {
  // Some Fancy Stuff
  return { code: "OK", payload }
} catch (error) {
  return { code: "FAIL", payload, metadata }
}
```
(- Also you not always want to return someting)

**Comment by ayntee** [comment]
Feel free to reopen
